---
apiVersion: "extensions/v1beta1"
kind: "ReplicaSet"
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "2"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "9"
    deployment.kubernetes.io/revision-history: "1"
  finalizers: []
  labels:
    app: "valengine"
    cluster: "valengine-prod"
    load-balancer-valengine-prod: "true"
    pod-template-hash: "3213935138"
    replication-controller: "valengine-prod-v006"
    stack: "prod"
    valengine-prod: "true"
    version: "6"
  name: "valengine-prod-v006"
  namespace: "default"
  ownerReferences: []
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchExpressions: []
    matchLabels:
      app: "valengine"
      cluster: "valengine-prod"
      pod-template-hash: "3213935138"
      replication-controller: "valengine-prod-v006"
      stack: "prod"
      valengine-prod: "true"
      version: "6"
  template:
    metadata:
      finalizers: []
      labels:
        app: "valengine"
        cluster: "valengine-prod"
        load-balancer-valengine-prod: "true"
        pod-template-hash: "3213935138"
        replication-controller: "valengine-prod-v006"
        stack: "prod"
        valengine-prod: "true"
        version: "6"
      ownerReferences: []
    spec:
      containers:
      - args: []
        command: []
        env: []
        image: "mibrxdll62xyo.azurecr.io/veritas/valengine:7"
        imagePullPolicy: "IfNotPresent"
        name: "veritas-valengine"
        ports:
        - containerPort: 6000
          name: "app"
          protocol: "TCP"
        - containerPort: 8000
          name: "health"
          protocol: "TCP"
        resources:
          requests:
            cpu: "250m"
            memory: "250Mi"
        terminationMessagePath: "/dev/termination-log"
        volumeMounts: []
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "docker-hub-registry"
      - name: "azure-container-registry"
      restartPolicy: "Always"
      securityContext:
        supplementalGroups: []
      terminationGracePeriodSeconds: 30
      volumes: []
status:
  availableReplicas: 2
  conditions: []
  fullyLabeledReplicas: 2
  observedGeneration: 7
  readyReplicas: 2
  replicas: 2
