---
apiVersion: "v1"
kind: "Service"
metadata:
  finalizers: []
  name: "valengine-dev"
  namespace: "default"
  ownerReferences: []
spec:
  clusterIP: "10.0.113.212"
  deprecatedPublicIPs: []
  externalIPs: []
  loadBalancerSourceRanges: []
  ports:
  - name: "app"
    port: 6000
    protocol: "TCP"
    targetPort: 6000
  - name: "health"
    port: 8000
    protocol: "TCP"
    targetPort: 8000
  selector:
    load-balancer-valengine-dev: "true"
  sessionAffinity: "None"
  type: "ClusterIP"
status:
  loadBalancer:
    ingress: []
